version: '3'
services:
  elasticsearch:
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - "discovery.type=single-node"
     - "xpack.security.enabled=false"
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.12"
  alertmanager2es:
    image: "simonpasquier/alertmanager2es"
    ports:
     - "9097:9097"
    command: "-esURL \"http://elasticsearch:9200\" -addr \":9097\""
  alertmanager:
    image: "prom/alertmanager"
    ports:
     - "9093:9093"
    volumes:
     - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"