version: '3'
services:
  elasticsearch:
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - "discovery.type=single-node"
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.2"
  alertmanager2es:
    image: "simonpasquier/alertmanager2es"
    ports:
     - "9097:9097"
    command: "-esURL \"http://localhost:9200\""
  alertmanager:
    image: "prom/alertmanager"
    ports:
     - "9093:9093"
    volumes:
     - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"